apiVersion: karpenter.k8s.alibabacloud/v1alpha1
kind: ECSNodeClass
metadata:
  name: defaultnodeclass
spec:
  vSwitchSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cluster-demonstration" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cluster-demonstration" # replace with your cluster name
  systemDisk:
    categories:
      - cloud
      - cloud_ssd
      - cloud_auto
    size: 60
  imageSelectorTerms:
    # ContainerOS only support x86_64 linux nodes, and it's faster to initialize
    - alias: ContainerOS
    # AlibabaCloudLinux3 only support x86_64/arm64 linux nodes
    #- alias: AlibabaCloudLinux3
